"""empty message

Revision ID: 30d07d18a259
Revises: 
Create Date: 2020-04-01 18:03:02.469905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d07d18a259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=True),
    sa.Column('clothes_type', sa.String(length=100), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsersClothes',
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Clothes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Clothes_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsersClothes')
    op.drop_table('users')
    op.drop_table('clothes')
    # ### end Alembic commands ###
