"""empty message

Revision ID: 61ecd5914d63
Revises: 30d07d18a259
Create Date: 2020-04-01 18:04:16.034437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ecd5914d63'
down_revision = '30d07d18a259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
